"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-19 14:58:27.631496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.CheckConstraint("category IN ('Security', 'Content Modeling', 'Content', 'Other Configurations')", name='ck_checks_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_checks_category'), 'checks', ['category'], unique=False)
    op.create_table('stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entries_count', sa.Integer(), nullable=False),
    sa.Column('assets_count', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bucket', sa.String(length=30), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("bucket IN ('Actions Required', 'Areas of Opportunity', 'Strengths', 'Not Applicable')", name='ck_check_results_bucket'),
    sa.CheckConstraint("status IN ('passed', 'failed', 'skipped')", name='ck_check_results_status'),
    sa.CheckConstraint('entity_count >= 0', name='ck_check_results_entity_count'),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stack_id', 'check_id')
    )
    op.create_index(op.f('ix_check_results_check_id'), 'check_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_check_results_stack_id'), 'check_results', ['stack_id'], unique=False)
    op.create_index(op.f('ix_check_results_status'), 'check_results', ['status'], unique=False)
    op.create_table('failed_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_result_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=300), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['check_result_id'], ['check_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_entities_check_result_id'), 'failed_entities', ['check_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_entities_check_result_id'), table_name='failed_entities')
    op.drop_table('failed_entities')
    op.drop_index(op.f('ix_check_results_status'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_stack_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_check_id'), table_name='check_results')
    op.drop_table('check_results')
    op.drop_table('stacks')
    op.drop_index(op.f('ix_checks_category'), table_name='checks')
    op.drop_table('checks')
    # ### end Alembic commands ###
